services:
  web:
    build: .
    container_name: web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8009:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  celery:
    build: .
    container_name: celery
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
